version: '3.8'

services:
  todo-app:
    build: .
    ports:
      - "80:80"
    container_name: todo-list-app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
